library(tidyverse)
library(ggplot)

#Ranking for Spanish language classes
my_df1 <- read.csv("Preference for Spanish Class.csv")


glimpse(my_df1)

Observations: 92
Variables: 19
$ Participant.ID               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2...
$ First_FTF_InstructorPref     <int> 3, 2, 2, 1, 1, 2, NA, 2, 1, 2, 2, 1, 4, 1, 1, 1, 3, 2, 2, 3, 2, 2, 2, 1, 3, ...
$ Second_FTF_InstructorPref    <int> 4, 3, 1, 2, 2, 1, NA, 1, 2, 3, 1, 2, 3, 2, 2, 3, 2, 1, 1, 2, 1, 1, 3, 2, 4, ...
$ Third_FTF_InstructorPref     <int> 2, 1, 3, 3, 3, 3, NA, 4, 3, 4, 3, 3, 2, 4, 3, 4, 4, 3, 3, 4, 3, 3, 1, 3, 2, ...
$ Fourth_FTF_InstructorPref    <fct> 1, 4, 4, 4, 4, 4, , 3, 4, 1, 4, 4, 1, 3, 4, 2, 1, 4, 4, 1, 4, 4, 4, 4, 1, 4,...
$ First_Online_InstructorPref  <int> NA, 2, 2, 1, 2, 2, NA, 2, 1, 2, 2, 1, 4, NA, 1, 1, 2, 2, 1, 3, 2, 2, 2, 1, 3...
$ Second_Online_InstructorPref <int> NA, 3, 1, 2, 1, 1, NA, 1, 2, 3, 1, 2, 3, NA, 2, 3, 3, 1, 2, 4, 1, 1, 3, 2, 4...
$ Third_Online_InstructorPref  <int> NA, 1, 3, 3, 3, 3, NA, 4, 3, 4, 3, 3, 2, NA, 3, 4, 4, 3, 3, 2, 3, 3, 1, 3, 2...
$ Fourth_Online_InstructorPref <int> NA, 4, 4, 4, 4, 4, NA, 3, 4, 1, 4, 4, 1, NA, 4, 2, 1, 4, 4, 1, 4, 4, 4, 4, 1...
$ X                            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.1                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.2                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.3                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.4                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.5                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.6                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.7                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.8                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.9                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...

tidy_df1 <- my_df1 %>% 
  rename(., id = Participant.ID) %>% 
  gather(., type, choice, -id) %>% 
  separate(., type, into = c('selection', 'type', 'trash'), sep = "_") %>% 
  mutate(., choice = as.factor(choice), 
         choice_char = fct_recode(choice, type_1 = '1', type_2 = '2', 
                                  type_3 = '3', type_4 = '4')) %>% 
  dplyr::select(., -trash)

tidy_df1 %>% 
  filter(., choice_char != "0") %>% 
  mutate(., selection = fct_relevel(selection, 'First', 'Second', 
                                    'Third', 'Fourth')) %>% 
  ggplot(., aes(x = choice_char)) + 
  facet_grid(type ~ selection) + 
  geom_histogram(stat = "count", fill = 'steelblue3', color = 'black') + labs(title = "Students' Instructor Ranking for Spanish Language Class", x = "Instructor Type", y = "Count")

#Ranking for Heritage Classes 

my_df2 <- read.csv("Preference for HS.csv")


glimpse(my_df2)

Observations: 92
Variables: 19
$ Participant.ID               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2...
$ First_FTF_InstructorPref     <int> 3, 2, 2, 1, 1, 2, NA, 2, 1, 2, 2, 1, 4, 1, 1, 1, 3, 2, 2, 3, 2, 2, 2, 1, 3, ...
$ Second_FTF_InstructorPref    <int> 4, 3, 1, 2, 2, 1, NA, 1, 2, 3, 1, 2, 3, 2, 2, 3, 2, 1, 1, 2, 1, 1, 3, 2, 4, ...
$ Third_FTF_InstructorPref     <int> 2, 1, 3, 3, 3, 3, NA, 4, 3, 4, 3, 3, 2, 4, 3, 4, 4, 3, 3, 4, 3, 3, 1, 3, 2, ...
$ Fourth_FTF_InstructorPref    <fct> 1, 4, 4, 4, 4, 4, , 3, 4, 1, 4, 4, 1, 3, 4, 2, 1, 4, 4, 1, 4, 4, 4, 4, 1, 4,...
$ First_Online_InstructorPref  <int> NA, 2, 2, 1, 2, 2, NA, 2, 1, 2, 2, 1, 4, NA, 1, 1, 2, 2, 1, 3, 2, 2, 2, 1, 3...
$ Second_Online_InstructorPref <int> NA, 3, 1, 2, 1, 1, NA, 1, 2, 3, 1, 2, 3, NA, 2, 3, 3, 1, 2, 4, 1, 1, 3, 2, 4...
$ Third_Online_InstructorPref  <int> NA, 1, 3, 3, 3, 3, NA, 4, 3, 4, 3, 3, 2, NA, 3, 4, 4, 3, 3, 2, 3, 3, 1, 3, 2...
$ Fourth_Online_InstructorPref <int> NA, 4, 4, 4, 4, 4, NA, 3, 4, 1, 4, 4, 1, NA, 4, 2, 1, 4, 4, 1, 4, 4, 4, 4, 1...
$ X                            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.1                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.2                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.3                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.4                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.5                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.6                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.7                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.8                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.9                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...

tidy_df2 <- my_df2 %>% 
  rename(., id = Participant.ID) %>% 
  gather(., type, choice, -id) %>% 
  separate(., type, into = c('selection', 'type', 'trash'), sep = "_") %>% 
  mutate(., choice = as.factor(choice), 
         choice_char = fct_recode(choice, type_1 = '1', type_2 = '2', 
                                  type_3 = '3', type_4 = '4')) %>% 
  dplyr::select(., -trash)

tidy_df2 %>% 
  filter(., choice_char != "0") %>% 
  mutate(., selection = fct_relevel(selection, 'First', 'Second', 
                                    'Third', 'Fourth')) %>% 
  ggplot(., aes(x = choice_char)) + 
  facet_grid(type ~ selection) + 
  geom_histogram(stat = "count", fill = 'steelblue3', color = 'black') + labs(title = "Students' Instructor Ranking for Heritage Classes", x = "Instructor Type", y = "Count")


#Ranking for Content Classes 
my_df3 <- read.csv("Preference for Content.csv")


glimpse(my_df3)

Observations: 92
Variables: 19
$ Participant.ID               <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2...
$ First_FTF_InstructorPref     <int> 3, 2, 2, 1, 1, 2, NA, 2, 1, 2, 2, 1, 4, 1, 1, 1, 3, 2, 2, 3, 2, 2, 2, 1, 3, ...
$ Second_FTF_InstructorPref    <int> 4, 3, 1, 2, 2, 1, NA, 1, 2, 3, 1, 2, 3, 2, 2, 3, 2, 1, 1, 2, 1, 1, 3, 2, 4, ...
$ Third_FTF_InstructorPref     <int> 2, 1, 3, 3, 3, 3, NA, 4, 3, 4, 3, 3, 2, 4, 3, 4, 4, 3, 3, 4, 3, 3, 1, 3, 2, ...
$ Fourth_FTF_InstructorPref    <fct> 1, 4, 4, 4, 4, 4, , 3, 4, 1, 4, 4, 1, 3, 4, 2, 1, 4, 4, 1, 4, 4, 4, 4, 1, 4,...
$ First_Online_InstructorPref  <int> NA, 2, 2, 1, 2, 2, NA, 2, 1, 2, 2, 1, 4, NA, 1, 1, 2, 2, 1, 3, 2, 2, 2, 1, 3...
$ Second_Online_InstructorPref <int> NA, 3, 1, 2, 1, 1, NA, 1, 2, 3, 1, 2, 3, NA, 2, 3, 3, 1, 2, 4, 1, 1, 3, 2, 4...
$ Third_Online_InstructorPref  <int> NA, 1, 3, 3, 3, 3, NA, 4, 3, 4, 3, 3, 2, NA, 3, 4, 4, 3, 3, 2, 3, 3, 1, 3, 2...
$ Fourth_Online_InstructorPref <int> NA, 4, 4, 4, 4, 4, NA, 3, 4, 1, 4, 4, 1, NA, 4, 2, 1, 4, 4, 1, 4, 4, 4, 4, 1...
$ X                            <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.1                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.2                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.3                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.4                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.5                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.6                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.7                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.8                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ X.9                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...

tidy_df3 <- my_df3 %>% 
  rename(., id = Participant.ID) %>% 
  gather(., type, choice, -id) %>% 
  separate(., type, into = c('selection', 'type', 'trash'), sep = "_") %>% 
  mutate(., choice = as.factor(choice), 
         choice_char = fct_recode(choice, type_1 = '1', type_2 = '2', 
                                  type_3 = '3', type_4 = '4')) %>% 
  dplyr::select(., -trash)

tidy_df3 %>% 
  filter(., choice_char != "0") %>% 
  mutate(., selection = fct_relevel(selection, 'First', 'Second', 
                                    'Third', 'Fourth')) %>% 
  ggplot(., aes(x = choice_char)) + 
  facet_grid(type ~ selection) + 
  geom_histogram(stat = "count", fill = 'steelblue3', color = 'black') + labs(title = "Students' Instructor Ranking for Content Classes", x = "Instructor Type", y = "Count")



